config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :exercises
      resources :equipaments
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/equipament.rb
class Equipament < ApplicationRecord
  validates :name, presence: true
end

app/controllers/api/v1/equipaments_controller.rb
class Api::V1::EquipamentsController < ActionController::API
  before_action :set_equipament, only: %i[ show edit update destroy ]

  # GET /equipaments or /equipaments.json
  def index
    @equipaments = Equipament.all
  end

  # GET /equipaments/1 or /equipaments/1.json
  def show
  end

  # GET /equipaments/new
  def new
    @equipament = Equipament.new
  end

  # GET /equipaments/1/edit
  def edit
  end

  # POST /equipaments or /equipaments.json
  def create
    @equipament = Equipament.new(equipament_params)

    respond_to do |format|
      if @equipament.save
        format.html { redirect_to @equipament, notice: "Equipament was successfully created." }
        format.json { render :show, status: :created, location: @equipament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipaments/1 or /equipaments/1.json
  def update
    respond_to do |format|
      if @equipament.update(equipament_params)
        format.html { redirect_to @equipament, notice: "Equipament was successfully updated." }
        format.json { render :show, status: :ok, location: @equipament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipaments/1 or /equipaments/1.json
  def destroy
    @equipament.destroy!

    respond_to do |format|
      format.html { redirect_to equipaments_path, status: :see_other, notice: "Equipament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipament
      @equipament = Equipament.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def equipament_params
      params.expect(equipament: [ :name ])
    end
end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationController
  before_action :set_equipament, only: %i[ show edit update destroy ]

  # GET /equipaments or /equipaments.json
  def index
    @equipaments = Equipament.all
  end

  # GET /equipaments/1 or /equipaments/1.json
  def show
  end

  # GET /equipaments/new
  def new
    @equipament = Equipament.new
  end

  # GET /equipaments/1/edit
  def edit
  end

  # POST /equipaments or /equipaments.json
  def create
    @equipament = Equipament.new(equipament_params)

    respond_to do |format|
      if @equipament.save
        format.html { redirect_to @equipament, notice: "Equipament was successfully created." }
        format.json { render :show, status: :created, location: @equipament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipaments/1 or /equipaments/1.json
  def update
    respond_to do |format|
      if @equipament.update(equipament_params)
        format.html { redirect_to @equipament, notice: "Equipament was successfully updated." }
        format.json { render :show, status: :ok, location: @equipament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipaments/1 or /equipaments/1.json
  def destroy
    @equipament.destroy!

    respond_to do |format|
      format.html { redirect_to equipaments_path, status: :see_other, notice: "Equipament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipament
      @equipament = Equipament.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def equipament_params
      params.expect(equipament: [ :name ])
    end
end

app/views/equipaments/_equipament.html.erb
<div id="<%= dom_id equipament %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= equipament.name %>
  </p>

</div>

app/views/equipaments/_form.html.erb
<%= form_with(model: equipament, class: "contents") do |form| %>
  <% if equipament.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(equipament.errors.count, "error") %> prohibited this equipament from being saved:</h2>

      <ul>
        <% equipament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/equipaments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing equipament</h1>

  <%= render "form", equipament: @equipament %>

  <%= link_to "Show this equipament", @equipament, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to equipaments", equipaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/equipaments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Equipaments" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Equipaments</h1>
    <%= link_to "New equipament", new_equipament_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="equipaments" class="min-w-full">
    <% @equipaments.each do |equipament| %>
      <%= render equipament %>
      <p>
        <%= link_to "Show this equipament", equipament, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/equipaments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New equipament</h1>

  <%= render "form", equipament: @equipament %>

  <%= link_to "Back to equipaments", equipaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/equipaments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @equipament %>

    <%= link_to "Edit this equipament", edit_equipament_path(@equipament), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to equipaments", equipaments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this equipament", @equipament, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>